#CI项目
name: znm2-lede-ssrp

#CI计划
on:
  # 手动执行
  workflow_dispatch:

#CI权限
permissions: write-all

#CI任务
jobs:
  build:
    name: znm2-lede-ssrp

    #调用公用编译核心WRT-CORE.yml
    uses: ./.github/workflows/core.yml
    with:
      #编译平台
      TARGET: znm2-lede-ssrp
      #源码
      REPO_SOURCE: lede
      #源码地址
      REPO_URL: https://github.com/coolsnowwolf/lede.git
      #源码分支
      REPO_BRANCH: master
      #软件源
      FEEDS_CONF: ./feeds/lede/feeds.conf.default
      #配置文件
      CONFIG_FILE: ./config/lede/znm2-lede.config
      #自定义脚本1
      DIY_P1_SH: ./scripts/lede/diy-part1.sh
      #自定义脚本2
      DIY_P2_SH: ./scripts/lede/diy-part2.sh
      #预安装脚本
      PRE_INSTALL_SH: ./scripts/pre_install.sh
